<?php

namespace CaradvisorBundle\Repository;

/**
 * ReviewRepairRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepairRepository extends \Doctrine\ORM\EntityRepository
{
    public function getReviewsForSlides()
    {
        $qb = $this->createQueryBuilder("r")
                    ->select("r.review", "r.city", "r.dateReview", "r.dealerName", "u.userName")
                    ->join("r.user", "u")
                    ->orderBy("r.dateReview", "desc")
                    ->setMaxResults(3)
                    ->getQuery();

        return $qb->getResult();

    }
}
