<?php

namespace CaradvisorBundle\Repository;

/**
 * ReviewBuyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewBuyRepository extends \Doctrine\ORM\EntityRepository
{
}
