CaradvisorBundle\Entity\Review:
    type: entity
    table: review
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        proname:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        lastname:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        firstname:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        city:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        review:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
